name: productivity_app1
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - libcxx=21.1.8
  - libexpat=2.7.4
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - python=3.11.14
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - click==8.3.1
      - fastapi==0.129.0
      - h11==0.16.0
      - idna==3.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - starlette==0.52.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uvicorn==0.41.0
prefix: /Users/onyxairways/miniconda3/envs/productivity_app1
